"""Generate the Microsoft refresh token used by the email integration.

This script is meant to be run manually during local setup. It uses Microsoft's
device authorization flow, which is convenient for command-line tooling because
the user can complete the login in a browser while the script waits in the
terminal for the authorization result.
"""

import os
from typing import Any

import msal
from dotenv import load_dotenv

load_dotenv()

GRAPH_AUTHORITY = "https://login.microsoftonline.com/consumers"
GRAPH_SCOPES = ["Mail.Send"]


def build_public_client() -> msal.PublicClientApplication:
    """Create the MSAL client used throughout the device-flow exchange.

    Returns:
        A configured ``PublicClientApplication`` instance targeting Microsoft's
        consumer tenant.

    Raises:
        ValueError: If the Microsoft application client ID is missing from the
            current environment.
    """
    # The client ID identifies the Azure application that is allowed to request
    # tokens on behalf of the Outlook account.
    client_id = os.getenv("MICROSOFT_CLIENT_ID")
    if not client_id:
        raise ValueError("The MICROSOFT_CLIENT_ID environment variable is not set.")

    # Personal Outlook accounts authenticate against the ``consumers`` tenant.
    return msal.PublicClientApplication(client_id, authority=GRAPH_AUTHORITY)


def start_device_flow(app: msal.PublicClientApplication) -> dict[str, Any]:
    """Start the browser-based challenge required by the device flow.

    Args:
        app: The MSAL public client already configured for this project.

    Returns:
        The flow payload returned by MSAL, including the verification code and
        browser URL that the user must visit.

    Raises:
        ValueError: If Microsoft does not return the expected device-flow data.
    """
    # ``initiate_device_flow`` creates the one-time challenge that links the
    # terminal session to the browser login the user will complete next.
    flow = app.initiate_device_flow(scopes=GRAPH_SCOPES)

    # ``user_code`` is a reliable indicator that MSAL returned a real device
    # flow payload rather than an error shape.
    if "user_code" not in flow:
        raise ValueError("Failed to start the device flow. Check the application credentials.")

    return flow


def acquire_refresh_token(
    app: msal.PublicClientApplication,
    flow: dict[str, Any],
) -> str:
    """Wait for the browser login to finish and extract the refresh token.

    Args:
        app: The MSAL public client handling the token exchange.
        flow: The device-flow payload previously generated by ``start_device_flow``.

    Returns:
        The refresh token that should be persisted in the local ``.env`` file.

    Raises:
        ValueError: If the authentication flow completes without a refresh token.
    """
    # MSAL polls Microsoft's device-flow endpoint until the user authenticates
    # or the challenge expires.
    result = app.acquire_token_by_device_flow(flow)

    # The refresh token is the only value we need to persist for the webhook.
    refresh_token = result.get("refresh_token")
    if refresh_token:
        return refresh_token

    raise ValueError(
        "Unable to get a refresh token: "
        f"{result.get('error_description', 'No error description was returned.')}"
    )


def main() -> None:
    """Run the complete token bootstrap flow from the command line.

    The command output is intentionally simple: first the browser instructions,
    then the exact ``.env`` line that should be copied into local configuration.
    """
    # Build the MSAL client once and reuse it for the full interactive flow.
    app = build_public_client()

    # Generate the one-time device challenge and print the human-readable
    # instructions returned by Microsoft.
    flow = start_device_flow(app)

    print(flow["message"])

    # Once the user finishes the browser login, print the refresh token in a
    # copy-paste-friendly format for the project's environment file.
    refresh_token = acquire_refresh_token(app, flow)
    print("\nSUCCESS! Add the following line to your .env file:")
    print(f"MICROSOFT_REFRESH_TOKEN={refresh_token}")

if __name__ == "__main__":
    main()